name: CPUTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd CPUTests
      run: cd CPUTests
    - name: make
      run: make
    - name: cputest
      run: ./cputest
