name: CPUTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./CPUTests

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: cputest
      run: ./cputest
